# Build Agent
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o agent ./cmd/agent

# Final Image
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/agent .
# Create data directory
RUN mkdir -p data
EXPOSE 8080
CMD ["./agent"]
